name: Ubuntu Environment Test

on:
  push:
    branches: [ main ]
  schedule:
    # Run weekly to ensure Ubuntu 24.04 compatibility
    - cron: '0 0 * * 0'

jobs:
  ubuntu-compatibility:
    runs-on: ubuntu-24.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: System Information
      run: |
        echo "=== Ubuntu Release Information ==="
        cat /etc/os-release
        echo ""
        echo "=== System Resources ==="
        free -h
        df -h
        echo ""
        echo "=== Available Development Tools ==="
        which python3 && python3 --version
        which node && node --version
        which rustc && rustc --version || echo "Rust not installed by default"
        which git && git --version
        which curl && curl --version | head -1
        
    - name: Install Common Development Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget git
        
    - name: Test Package Installation
      run: |
        echo "Testing package manager on Ubuntu 24.04..."
        sudo apt-get install -y htop
        htop --version
        
    - name: Development Environment Setup Test
      run: |
        echo "=== Testing development environment setup ==="
        # Test Python development setup
        python3 -m pip install --user virtualenv
        python3 -m virtualenv test_env
        source test_env/bin/activate
        pip install requests
        python3 -c "import requests; print('Python environment: OK')"
        deactivate
        
        # Test Node.js setup
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm --version
        echo "console.log('Node.js environment: OK')" | node
        
        # Test basic Rust setup (if needed for this project)
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        rustc --version